// <auto-generated />
namespace BlackMesa.MyStack.Main.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class ProtoInit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProtoInit));
        
        string IMigrationMetadata.Id
        {
            get { return "201402061717265_ProtoInit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
